### ISSUE TITLE
provide an ability to disable logging

### ISSUE THREAD

**Issue by explicitcall** [WeltN24/Carlos#109]
Currently, there is no way to disable log output emitted by Carlos. 

While log levels are specified, there is no way to restrict Carlos to emitting output only when it exceeds a certain threshold level.

**Comment by explicitcall** [comment]
As an option, logging could be restricted only to debug builds. It's really worrying to see debug output from Carlos in release builds.

**Comment by vittoriom** [comment]
Hi @explicitcall, thanks for taking the time to create this issue! 
When we decided how to handle logging in Carlos, we went for the most flexible approach that didn't require us to code a complete logging framework, that is the ability to plug-in your own logging library.
If you want the output of Carlos to only be printed if exceeding the `.Warning` level, or if you want to completely silent it for release builds, or if you want to route it to a file, or whatever else: just do

```swift
Carlos.Logger.output = { message, level in 
   myLibrary.log(message) //Plug here your logging library.
}
````

We're using [XCGLogger](https://github.com/DaveWoodCom/XCGLogger) in production and we are able to only log in debug builds without too much effort.
Is this solution fine for you?

**Comment by explicitcall** [comment]
@vittoriom great, that's fantastic and flexible! Although, this solution wasn't obvious from the source code and I didn't see anything related in the docs.  Can this be mentioned anywhere in Carlos docs from now on, so that it's easier to find for other people trying to resolve the same issue?

**Comment by vittoriom** [comment]
Absolutely, I think I totally overlooked the section about logging! I'll add it straight away to the README and close the issue when I'll be done. Thanks again!

**Comment by vittoriom** [comment]
For future reference:

https://github.com/WeltN24/Carlos#logging
