### ISSUE TITLE
Carlos can support expire time like AwesomeCache

### ISSUE THREAD

**Issue by arden** [WeltN24/Carlos#134]
Carlos can support expire time like AwesomeCache?

**Comment by vittoriom** [comment]
Hi @arden, currently Carlos doesn't support expiration time of cached entries. This feature is tracked in #89 but there is no ETA at the moment.
If you have any ideas how to integrate this in generic `CacheLevel` instances, both out of the box and user-provided, feel free to drop them here!

Thanks and have a good Easter

**Comment by vittoriom** [comment]
I'll close this since the development can be tracked in the existing issue.
