### ISSUE TITLE
Can't build with Carthage

### ISSUE THREAD

**Issue by rizumita** [WeltN24/Carlos#153]
I tried building with Carthage, but error occurred.

```
xcodebuild: error: Scheme PiedPiper is not currently configured for the build action.
```

How can I build?

**Comment by vittoriom** [comment]
Hi @rizumita, did you try to build `Carlos` after checking out the repository, or did you try to build `Carlos` as a dependency part of your `Cartfile`?

**Comment by rizumita** [comment]
Hi @vittoriom 

I'm using Carlos in my project.
I wrote following Cartfile.
```
github "ReactiveCocoa/ReactiveCocoa"
github "WeltN24/Carlos"
```

**Comment by vittoriom** [comment]
The `Cartfile` looks fine, can you please try to remove the Carlos folder from `Carthage/Checkouts` and run `carthage update Carlos --platform iOS`? 

With the latest version of `Carlos` (0.8), I extracted `PiedPiper` to its own repository and maybe it's better to run a clean update.

Please let me know if this solves the issue

**Comment by rizumita** [comment]
@vittoriom 
I became to be able to build after deleting Carthage folder and DerivedData folder.
Thank you for your advise!

**Comment by vittoriom** [comment]
No problem, sorry for the inconvenience and I'm glad everything is sorted out!
