### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by vittoriom** [WeltN24/Carlos#160]

**Comment by ivanruizscm** [comment]
Hi @vittoriom, congrats for the library :)
When its expected to migrate to swift 3? is anybody working on it?

**Comment by vittoriom** [comment]
Hi @ivanruizscm, thanks!

I started migrating to Swift 3 a long time ago, and then I stopped because there was no support for Quick/Nimble (the framework we use to unit test Carlos).

I didn't catch up with their progress anymore, if they support Xcode 8 with Swift 3, the migration should be possible and not too much hassle (at least to make it build).

**Comment by ivanruizscm** [comment]
Both supports Xcode8/Swift 3.
You can open a branch for it so if anyone is encouraged can start 💃

**Comment by akaralar** [comment]
@vittoriom do you still have that swift3 work around? Maybe you can push to a branch and people interested can send PRs?

**Comment by vittoriom** [comment]
Sure, I'll push the branch this evening, even though some new features that are now in develop might be missing from there.. Then we can hopefully work together to make Quick/Nimble work! 👍

**Comment by vittoriom** [comment]
Sorry, I just realized I didn't actually start migrating Carlos but PiedPiper instead (which is a needed dependency anyway). It also uses Quick and Nimble and the branch is [here](https://github.com/WeltN24/PiedPiper/tree/swift3)

**Comment by vittoriom** [comment]
Hi everyone again, the migration of `PiedPiper` to Swift 3 is done, and I'll migrate `Carlos` too in the next days. Thanks for your patience!

**Comment by vittoriom** [comment]
Sorry for such a late reply, but I'm glad to announce that Swift 3 support is now on master! I will make a release for Carthage and a new version for CocoaPods immediately 👍
