### ISSUE TITLE
Add helper functions for most common caches

### ISSUE THREAD

**Issue by vittoriom** [WeltN24/Carlos#44]
It would be nice to add some public functions or maybe one helper class with a couple of methods on it, to create the most common caches (e.g. Memory -> Disk -> Network)

This way one doesn't have to always write the boilerplate code for simple usages

**Comment by vittoriom** [comment]
- Include dataCache function for NSURL keys and NSData values
- Include imageCache function for NSURL keys and UIImage values

- what else? @andresbrun

**Comment by andresbrun** [comment]
I would feel pretty confortable by using these two so far ;)

**Comment by vittoriom** [comment]
Added `dataCache()` and `imageCache()` static functions to the `CacheProvider` class.
The implementation is not really production-ready but the flaws will be addressed by follow-up issues.
