### ISSUE TITLE
Adding support to watchos 2

### ISSUE THREAD

**Issue by mohamedghonemi** [WeltN24/Carlos#57]
I think adding support for the watchos 2 would be very helpful

**Comment by vittoriom** [comment]
Hi @mohamedghonemi, thanks for your interest in Carlos! 

I'll try to add support for watchos 2 as soon as possible. 

I assigned this issue to the [0.2.1](https://github.com/WeltN24/Carlos/milestones/0.2.1) milestone, so it will be done together with Swift 2.0 support.

**Comment by mohamedghonemi** [comment]
Thanks a lot, I am waiting for it :)

**Comment by vittoriom** [comment]
Hi @mohamedghonemi, I added a new `Carlos (Watch)` framework for WatchOS 2, and from a quick test it looks like it can be successfully embedded in a WatchOS 2 App. I'll close the issue when the `swift2.0` branch will be merged in `master` (that is, when iOS 9 comes out), and I'll do additional tests during the weekend. I'll probably add some sample code for a WatchOS 2 App as well. 

In the mean time, it should work :)

**Comment by mohamedghonemi** [comment]
Thanks alot

**Comment by mohamedghonemi** [comment]
I had a problem when I added the files the my project :
/Carlos/MemoryWarning.swift:10:68: Use of unresolved identifier 'UIApplicationDidReceiveMemoryWarningNotification'

Do I have missed something in adding the files to  the project ?

**Comment by vittoriom** [comment]
Yes, I didn't update the `podspec` yet, but the `CarlosWatch` framework target doesn't contain the `MemoryWarning.swift` file. If you don't include that file, it should compile successfully. 
What errors do you have in DiskCacheLevel? Are you on the `swift2.0` branch?

**Comment by mohamedghonemi** [comment]
Yes I am using the swift2.0 branch.
But I was using the code downloaded from Github directly, not the pod so I had the file added to the project, so I removed it now and errors related to it disappeared.
Still DiskCacheLevel.swift gives these errors :
- /DiskCacheLevel.swift:23:79: 'lastPathComponent' is unavailable: Use lastPathComponent on NSURL instead.
- /DiskCacheLevel.swift:38:51: 'stringByAppendingPathComponent' is unavailable: Use URLByAppendingPathComponent on NSURL instead.

**Comment by vittoriom** [comment]
All right, this is maybe something that came up with the new Xcode beta? I'll investigate and fix it asap, most likely there is a cast to `NSString` needed. Thanks for reporting!

**Comment by vittoriom** [comment]
I just had some time to check the issue and yes, Beta 6 broke the code. I just pushed the fixes, sorry for the inconvenience
