### ISSUE TITLE
Improve MacOS support

### ISSUE THREAD

**Issue by vittoriom** [WeltN24/Carlos#62]
- [ ] Add memory warning support
- [ ] Add image cache support in CacheProvider

**Comment by rufferto** [comment]
macOS support coming back?

**Comment by vittoriom** [comment]
Hi @rufferto, unfortunately the development on Carlos by my side it's a bit slow due to other duties, and I'm not planning to add macOS support in the short term. A PR for that would be greatly welcome, though.
